import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useContext, useEffect, useState } from "react";

export type Lang = "es" | "en";

const T = {
  es: {
    appName: "PassPic PRO",
    appSub: "Fotos de Pasaporte con IA",
    langLabel: "Idioma",
    countryFormat: "Formato de País",
    allCountries: "Todos los Países",
    selectedFormat: "Formato seleccionado",
    takePhoto: "Tomar Foto",
    cameraFront: "delantera",
    cameraBack: "trasera",
    camera: "Cámara",
    uploadGallery: "Subir de Galería",
    tips: "Consejos para una foto perfecta",
    tipsList: [
      "Coloca tu cara directamente hacia la cámara",
      "Asegúrate de tener buena iluminación frontal",
      "Mantén expresión neutra, boca cerrada",
      "Usa ropa oscura para destacar contra fondo blanco",
    ],
    processing: "Procesando...",
    passportPhoto: "Foto de Pasaporte",
    qualityScore: "Puntuación de Calidad",
    validationChecks: "Verificaciones",
    photoSpecs: "Especificaciones",
    background: "Fondo",
    backgroundWhite: "Blanco (#FFFFFF)",
    share: "Compartir",
    download: "Descargar",
    myPhotos: "Mis Fotos",
    noPhotos: "Sin fotos aún",
    noPhotosSub: "Toma tu primera foto de pasaporte",
    frontCamera: "Cámara delantera",
    backCamera: "Cámara trasera",
    centerFace: "Centra tu cara dentro del marco",
    permRequired: "Permisos necesarios",
    permDesc: "PassPic PRO necesita los siguientes permisos para funcionar correctamente. Tu privacidad está protegida — nunca compartimos tus fotos.",
    permCamera: "Cámara",
    permCameraDesc: "Para tomar fotos directamente desde la app y generar tu foto de pasaporte.",
    permPhotos: "Fotos y Galería",
    permPhotosDesc: "Para seleccionar fotos existentes de tu galería y guardar tus fotos de pasaporte.",
    grantPerms: "Otorgar permisos",
    allGranted: "Todos los permisos otorgados",
    privacyNote: "Puedes cambiar estos permisos en cualquier momento desde los Ajustes de tu dispositivo.",
    required: "Requerido",
    excellent: "Excelente",
    good: "Bueno",
    fair: "Regular",
    needsImprovement: "Necesita mejora",
    faceDetected: "Cara detectada",
    faceDetectedOk: "Cara claramente visible",
    faceDetectedFail: "No se detectó cara en la foto",
    neutralExpr: "Expresión neutral",
    neutralExprOk: "Expresión es neutral",
    neutralExprFail: "Sonrisa detectada — mantén expresión neutral",
    eyesOpen: "Ojos abiertos",
    eyesOpenOk: "Ojos abiertos y visibles",
    eyesOpenFail: "Ojos parecen cerrados o parcialmente cerrados",
    goodLighting: "Buena iluminación",
    goodLightingOk: "Iluminación uniforme y brillante",
    goodLightingFail: "Iluminación irregular detectada",
    plainBg: "Fondo blanco",
    plainBgOk: "Fondo reemplazado correctamente",
    plainBgFail: "Fondo puede no estar completamente reemplazado",
    bgProcessing: "Procesando fondo blanco...",
    bgDone: "Fondo blanco aplicado",
    saveToGallery: "Guardar en Galería",
    savedToGallery: "¡Foto guardada en tu galería!",
    saveError: "No se pudo guardar la foto",
    docPreviewTitle: "Vista del Documento",
    docFormat: "Documento de pasaporte",
    saveAndShare: "Guardar y Compartir",
    tapToPreview: "Toca para ver el documento",
    takeFirstPhoto: "Tomar Primera Foto",
    noPhotosDesc: "Toma o sube una foto para generar tu foto de pasaporte",
    myPhotosTitle: "Mis Fotos",
    completedProcessing: (done: number, proc: number) =>
      `${done} completadas · ${proc} procesando`,
    deletePhoto: "Eliminar Foto",
    deleteConfirm: "¿Estás seguro de que quieres eliminar esta foto?",
    cancel: "Cancelar",
    delete: "Eliminar",
    goBack: "Volver",
    mobileOnly: "Solo en móvil",
    mobileOnlyDesc: "La descarga a galería solo está disponible en el dispositivo móvil.",
    permissionDenied: "Permiso denegado",
    country: "País",
    dimensions: "Dimensiones",
    resolution: "Resolución",
    outputSize: "Tamaño de salida",
    newPhoto: "Nueva Foto",
    whiteBgReady: "Fondo blanco · Listo para imprimir",
    saving: "Guardando...",
    saved: "¡Guardado!",
    selectCountry: "Seleccionar País",
    searchCountry: "Buscar país...",
    frontLabel: "Delantera",
    rearLabel: "Trasera",
    featuresList: ["Fondo Blanco con IA", "154+ Formatos de País", "Validación de Calidad"],
    cameraLabel: (facing: string) => `Cámara ${facing === "front" ? "delantera" : "trasera"}`,
    notes: "Notas",
    validated: "Validado",
    countriesAvailable: "países disponibles",
    editPhoto: "Editar Foto",
    editorTitle: "Ajustes de Imagen",
    brightness: "Brillo",
    contrast: "Contraste",
    saturation: "Saturación",
    sharpness: "Nitidez",
    rotateLeft: "Rotar izq.",
    rotateRight: "Rotar der.",
    flipH: "Voltear",
    applyEdits: "Aplicar",
    resetEdits: "Restablecer",
    applyingEdits: "Aplicando...",
    watchAdForHD: "Ver Anuncio · Descargar HD",
    watchAdSubtitle: "30 seg · Gratis para siempre",
    hdUnlocked: "¡Descarga HD desbloqueada!",
    hdSaving: "Guardando en alta resolución...",
    adLoading: "Cargando anuncio...",
    adError: "Anuncio no disponible, intenta de nuevo",
    icaoCertBtn: "Certificado ICAO",
    icaoReportTitle: "Foto Certificada ICAO",
    icaoReportSubtitle: "Esta foto cumple con los estándares internacionales de foto de pasaporte ICAO Doc 9303.",
    icaoReportPass: "APTA PARA EMBAJADA",
    icaoShareText: (country: string, score: number) =>
      `✅ Mi foto de pasaporte para ${country} fue verificada con PassPic PRO.\n📋 Puntuación ICAO: ${score}/100\n🌍 Compatible con estándares internacionales ICAO Doc 9303\n\nGenerada con PassPic PRO — descarga gratis`,
    shareReport: "Compartir Certificado",
    icaoChecks: "Verificaciones superadas",
    qualityGuarantee: "Garantía de Calidad",
  },
  en: {
    appName: "PassPic PRO",
    appSub: "AI Passport Photos",
    langLabel: "Language",
    countryFormat: "Country Format",
    allCountries: "All Countries",
    selectedFormat: "Selected format",
    takePhoto: "Take Photo",
    cameraFront: "front",
    cameraBack: "rear",
    camera: "Camera",
    uploadGallery: "Upload from Gallery",
    tips: "Tips for a perfect photo",
    tipsList: [
      "Face the camera directly",
      "Make sure you have good front lighting",
      "Keep a neutral expression, mouth closed",
      "Wear dark clothing to stand out against the white background",
    ],
    processing: "Processing...",
    passportPhoto: "Passport Photo",
    qualityScore: "Quality Score",
    validationChecks: "Validation Checks",
    photoSpecs: "Specifications",
    background: "Background",
    backgroundWhite: "White (#FFFFFF)",
    share: "Share",
    download: "Download",
    myPhotos: "My Photos",
    noPhotos: "No photos yet",
    noPhotosSub: "Take your first passport photo",
    frontCamera: "Front camera",
    backCamera: "Rear camera",
    centerFace: "Center your face in the frame",
    permRequired: "Permissions required",
    permDesc: "PassPic PRO needs the following permissions to work correctly. Your privacy is protected — we never share your photos.",
    permCamera: "Camera",
    permCameraDesc: "To take photos directly from the app and generate your passport photo.",
    permPhotos: "Photos & Gallery",
    permPhotosDesc: "To select existing photos from your gallery and save your passport photos.",
    grantPerms: "Grant permissions",
    allGranted: "All permissions granted",
    privacyNote: "You can change these permissions at any time from your device Settings.",
    required: "Required",
    excellent: "Excellent",
    good: "Good",
    fair: "Fair",
    needsImprovement: "Needs Improvement",
    faceDetected: "Face detected",
    faceDetectedOk: "Face clearly visible",
    faceDetectedFail: "No face detected in photo",
    neutralExpr: "Neutral expression",
    neutralExprOk: "Expression is neutral",
    neutralExprFail: "Smile detected — keep a neutral expression",
    eyesOpen: "Eyes open",
    eyesOpenOk: "Eyes are open and visible",
    eyesOpenFail: "Eyes appear closed or partially closed",
    goodLighting: "Good lighting",
    goodLightingOk: "Lighting is even and bright",
    goodLightingFail: "Uneven lighting detected",
    plainBg: "White background",
    plainBgOk: "Background replaced successfully",
    plainBgFail: "Background may not be fully replaced",
    bgProcessing: "Processing white background...",
    bgDone: "White background applied",
    saveToGallery: "Save to Gallery",
    savedToGallery: "Photo saved to your gallery!",
    saveError: "Could not save photo",
    docPreviewTitle: "Document Preview",
    docFormat: "Passport document",
    saveAndShare: "Save & Share",
    tapToPreview: "Tap to preview document",
    takeFirstPhoto: "Take First Photo",
    noPhotosDesc: "Take or upload a photo to generate your passport photo",
    myPhotosTitle: "My Photos",
    completedProcessing: (done: number, proc: number) =>
      `${done} completed · ${proc} processing`,
    deletePhoto: "Delete Photo",
    deleteConfirm: "Are you sure you want to delete this photo?",
    cancel: "Cancel",
    delete: "Delete",
    goBack: "Go Back",
    mobileOnly: "Mobile only",
    mobileOnlyDesc: "Saving to gallery is only available on mobile devices.",
    permissionDenied: "Permission denied",
    country: "Country",
    dimensions: "Dimensions",
    resolution: "Resolution",
    outputSize: "Output Size",
    newPhoto: "New Photo",
    whiteBgReady: "White background · Print-ready",
    saving: "Saving...",
    saved: "Saved!",
    selectCountry: "Select Country",
    searchCountry: "Search country...",
    frontLabel: "Front",
    rearLabel: "Rear",
    featuresList: ["AI White Background", "154+ Country Formats", "Quality Validation"],
    cameraLabel: (facing: string) => `${facing === "front" ? "Front" : "Rear"} camera`,
    notes: "Notes",
    validated: "Validated",
    countriesAvailable: "countries available",
    editPhoto: "Edit Photo",
    editorTitle: "Image Adjustments",
    brightness: "Brightness",
    contrast: "Contrast",
    saturation: "Saturation",
    sharpness: "Sharpness",
    rotateLeft: "Rotate L",
    rotateRight: "Rotate R",
    flipH: "Flip",
    applyEdits: "Apply",
    resetEdits: "Reset",
    applyingEdits: "Applying...",
    watchAdForHD: "Watch Ad · Download HD",
    watchAdSubtitle: "30 sec · Always free",
    hdUnlocked: "HD Download Unlocked!",
    hdSaving: "Saving in high resolution...",
    adLoading: "Loading ad...",
    adError: "Ad unavailable, please try again",
    icaoCertBtn: "ICAO Certificate",
    icaoReportTitle: "ICAO Certified Photo",
    icaoReportSubtitle: "This photo meets international passport photo standards ICAO Doc 9303.",
    icaoReportPass: "EMBASSY-READY",
    icaoShareText: (country: string, score: number) =>
      `✅ My passport photo for ${country} was verified with PassPic PRO.\n📋 ICAO Score: ${score}/100\n🌍 Compliant with ICAO Doc 9303 international standards\n\nGenerated with PassPic PRO — free download`,
    shareReport: "Share Certificate",
    icaoChecks: "Checks passed",
    qualityGuarantee: "Quality Guarantee",
  },
};

export type Translations = typeof T.es;

interface LangContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
}

const LangContext = createContext<LangContextValue>({
  lang: "es",
  setLang: () => {},
  t: T.es,
});

const LANG_KEY = "@passpic_lang";

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("es");

  useEffect(() => {
    AsyncStorage.getItem(LANG_KEY).then((v) => {
      if (v === "en" || v === "es") setLangState(v);
    });
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    AsyncStorage.setItem(LANG_KEY, l);
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t: T[lang] }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
