uploads = []
generated = []

[[outputs]]
id = "EQokTykWyCIFKVCVihZqn"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "PassPic PRO — Ícono de App"

[[outputs]]
id = "jF9PMp1hUhLriaQeZFsap"
uri = "file://artifacts/mobile/assets/images/splash-brand.png"
type = "image"
title = "PassPic PRO — Portada / Marca"

[[outputs]]
id = "wU19-hDuK-2rDgNiqYbPv"
uri = "file://artifacts/mobile/store-assets/passpic-mobile.tar.gz"
type = "unspecified"
title = "PassPic PRO - Código fuente (8.8 MB)"

[[outputs]]
id = "UNpVC3V6IpguqHaOSkkY7"
uri = "file://artifacts/mobile/store-assets/passpic-standalone.tar.gz"
type = "unspecified"
title = "PassPic PRO - Versión independiente (17.5 MB)"
